# Generated by Django 2.2.10 on 2021-05-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dept_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='program_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('financial_year', models.IntegerField()),
                ('no_of_participants', models.IntegerField(null=True)),
                ('depart_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dept_entre')),
            ],
        ),
    ]
