# Generated by Django 3.2.2 on 2021-05-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_skill',
            name='participant_idcard_alt_id_type',
            field=models.CharField(blank=True, choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Domicile Certificate', 'Domicile Certificate'), ('ST/SC Certificate', 'ST/SC Certificate'), ('Permanent Residential Certificate (PRC)', 'Permanent Residential Certificate (PRC)'), ('Driving License', 'Driving License'), ('Ration Card', 'Ration Card'), ('Birth Certificate issued by Government', 'Birth Certificate issued by Government'), ('BPL Card', 'BPL Card'), ('National Population Register (NPR) Card', 'National Population Register (NPR) CardIdentity proof by Gazetted officers'), ('Passport', 'Passport'), ('Jail Identification Card/ Number', 'Jail Identification Card/ Number'), ('School leaving certificate/10th certificate', 'School leaving certificate/10th certificate'), ('Letter of domicile from SDM/DM/Government Authority', 'Letter of domicile from SDM/DM/Government Authority')], max_length=100),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='participant_job_details_employment_status',
            field=models.CharField(blank=True, choices=[('Employed Through Registered Employer', 'Employed Through Registered Employer'), ('Opted for Higher Studies', 'Opted for Higher Studies'), ('Self Employed', 'Self Employed'), ('Up Skilled', 'Up Skilled'), ('Employed', 'Employed'), ('NA', 'NA'), ('Employed at Training Partner', 'Employed at Training Partner'), ('Employed at Other Firm', 'Employed at Other Firm')], max_length=100),
        ),
    ]
