# Generated by Django 2.2.10 on 2021-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant_entre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant_entre',
            name='mobile_entre_number',
        ),
        migrations.RemoveField(
            model_name='participant_skill',
            name='mobile_skill_number',
        ),
        migrations.AddField(
            model_name='participant_entre',
            name='mobile_entre_primary_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant_entre',
            name='mobile_entre_secondary_mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant_entre',
            name='primary_email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='participant_entre',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='participant_skill',
            name='mobile_skill_primary_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant_skill',
            name='mobile_skill_secondary_mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
