# Generated by Django 2.2.10 on 2021-05-13 13:44

import collectionfield.models.fields
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_entre',
            name='project_cost_CE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant_entre',
            name='project_cost_WC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='email',
            field=collectionfield.models.fields.CollectionField(collection_type=set, item_type=django.db.models.fields.EmailField, max_items=2),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_alt_id_type',
            field=models.CharField(blank=True, choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Domicile Certificate', 'Domicile Certificate'), ('ST/SC Certificate', 'ST/SC Certificate'), ('Permanent Residential Certificate (PRC)', 'Permanent Residential Certificate (PRC)'), ('Driving License', 'Driving License'), ('Ration Card', 'Ration Card'), ('Birth Certificate issued by Government', 'Birth Certificate issued by Government'), ('BPL Card', 'BPL Card'), ('National Population Register (NPR) Card', 'National Population Register (NPR) Card'), ('Identity proof by Gazetted officers', 'Identity proof by Gazetted officers'), ('Passport', 'Passport'), ('Jail Identification Card/ Number', 'Jail Identification Card/ Number'), ('School leaving certificate/10th certificate', 'School leaving certificate/10th certificate'), ('Letter of domicile from SDM/DM/Government Authority', 'Letter of domicile from SDM/DM/Government Authority')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='mobile_entre_mobile_number',
            field=collectionfield.models.fields.CollectionField(collection_type=set, item_type=int, max_items=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_alt_id_type',
            field=models.CharField(blank=True, choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Domicile Certificate', 'Domicile Certificate'), ('ST/SC Certificate', 'ST/SC Certificate'), ('Permanent Residential Certificate (PRC)', 'Permanent Residential Certificate (PRC)'), ('Driving License', 'Driving License'), ('Ration Card', 'Ration Card'), ('Birth Certificate issued by Government', 'Birth Certificate issued by Government'), ('BPL Card', 'BPL Card'), ('National Population Register (NPR) Card', 'National Population Register (NPR) Card'), ('Identity proof by Gazetted officers', 'Identity proof by Gazetted officers'), ('Passport', 'Passport'), ('Jail Identification Card/ Number', 'Jail Identification Card/ Number'), ('School leaving certificate/10th certificate', 'School leaving certificate/10th certificate'), ('Letter of domicile from SDM/DM/Government Authority', 'Letter of domicile from SDM/DM/Government Authority')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='mobile_skill_mobile_number',
            field=collectionfield.models.fields.CollectionField(collection_type=set, item_type=int, max_items=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='participant_job_details_employment_status',
            field=models.CharField(blank=True, choices=[('Employed Through Registered Employer', 'Employed Through Registered Employer'), ('Opted for Higher Studies', 'Opted for Higher Studies'), ('Self Employed', 'Self Employed'), ('Up Skilled', 'Up Skilled'), ('Employed', 'Employed'), ('NA', 'NA'), ('Employed at Training Partner', 'Employed at Training Partner'), ('Employed at Other Firm', 'Employed at Other Firm')], max_length=100),
        ),
    ]
