# Generated by Django 2.2.10 on 2021-07-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant_aware',
            name='total',
        ),
        migrations.RemoveField(
            model_name='participant_capac',
            name='total',
        ),
    ]
