# Generated by Django 2.2.10 on 2021-05-11 10:23

import collectionfield.models.fields
from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant_entre',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='participant_entre',
            name='primary_mobile_number',
        ),
        migrations.RemoveField(
            model_name='participant_entre',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='participant_entre',
            name='secondary_mobile_number',
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='email',
            field=collectionfield.models.fields.CollectionField(collection_type=set, item_type=django.db.models.fields.CharField, max_length=10),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='mobile_number',
            field=collectionfield.models.fields.CollectionField(collection_type=set, item_type=int, max_length=10),
        ),
    ]
