# Generated by Django 2.2.10 on 2021-05-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_aadhaar_ref_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_alt_id_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_alt_id_type',
            field=models.CharField(blank=True, choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Domicile Certificate', 'Domicile Certificate'), ('ST/SC Certificate', 'ST/SC Certificate'), ('Permanent Residential Certificate (PRC)', 'Permanent Residential Certificate (PRC)'), ('Driving License', 'Driving License'), ('Ration Card', 'Ration Card'), ('Birth Certificate issued by Government', 'Birth Certificate issued by Government'), ('BPL Card', 'BPL Card'), ('National Population Register (NPR) Card', 'National Population Register (NPR) CardIdentity proof by Gazetted officers'), ('Passport', 'Passport'), ('Jail Identification Card/ Number', 'Jail Identification Card/ Number'), ('School leaving certificate/10th certificate', 'School leaving certificate/10th certificate'), ('Letter of domicile from SDM/DM/Government Authority', 'Letter of domicile from SDM/DM/Government Authority')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_id_type',
            field=models.CharField(blank=True, choices=[('Alternate ID', 'Alternate ID'), ('Aadhar ID', 'Aadhar ID')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_aadhaar_ref_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_alt_id_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_alt_id_type',
            field=models.CharField(blank=True, choices=[('PAN Card', 'PAN Card'), ('Voter ID Card', 'Voter ID Card'), ('Domicile Certificate', 'Domicile Certificate'), ('ST/SC Certificate', 'ST/SC Certificate'), ('Permanent Residential Certificate (PRC)', 'Permanent Residential Certificate (PRC)'), ('Driving License', 'Driving License'), ('Ration Card', 'Ration Card'), ('Birth Certificate issued by Government', 'Birth Certificate issued by Government'), ('BPL Card', 'BPL Card'), ('National Population Register (NPR) Card', 'National Population Register (NPR) CardIdentity proof by Gazetted officers'), ('Passport', 'Passport'), ('Jail Identification Card/ Number', 'Jail Identification Card/ Number'), ('School leaving certificate/10th certificate', 'School leaving certificate/10th certificate'), ('Letter of domicile from SDM/DM/Government Authority', 'Letter of domicile from SDM/DM/Government Authority')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_id_type',
            field=models.CharField(blank=True, choices=[('Alternate ID', 'Alternate ID'), ('Aadhar ID', 'Aadhar ID')], max_length=25, null=True),
        ),
    ]
