# Generated by Django 3.2.2 on 2021-05-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_proof', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=25)),
                ('project_identified', models.CharField(max_length=50)),
                ('items_to_be_manufactured', models.CharField(max_length=50)),
                ('place_of_unit', models.CharField(max_length=40)),
                ('self_or_bank_financed', models.CharField(max_length=20)),
                ('own_contribution_amount', models.IntegerField()),
                ('date_of_loan_release', models.DateField()),
                ('commencement_date', models.DateField()),
                ('no_of_persons_employed', models.IntegerField()),
                ('program_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.program_entre')),
            ],
        ),
        migrations.CreateModel(
            name='participant_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=25)),
                ('dob', models.DateField()),
                ('email', models.CharField(blank=True, max_length=25, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=25)),
                ('fathers_name', models.CharField(blank=True, max_length=25)),
                ('mothers_name', models.CharField(blank=True, max_length=25)),
                ('religion', models.CharField(blank=True, max_length=25)),
                ('category', models.CharField(blank=True, max_length=25)),
                ('education_level', models.CharField(blank=True, max_length=25)),
                ('pa_same_as_ca', models.CharField(blank=True, max_length=25)),
                ('training_status', models.CharField(blank=True, max_length=25)),
                ('heard_about_us', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='dept_entre',
            name='Category',
        ),
        migrations.AddField(
            model_name='dept_entre',
            name='category_ent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='program_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('financial_year', models.DateField()),
                ('trade', models.CharField(blank=True, max_length=100)),
                ('no_of_participants', models.IntegerField(null=True)),
                ('depart_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dept_entre')),
            ],
        ),
        migrations.CreateModel(
            name='program_address_state_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=25)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program_skill')),
            ],
        ),
        migrations.CreateModel(
            name='program_address_location_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program_skill')),
            ],
        ),
        migrations.CreateModel(
            name='program_address_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('program_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.program_entre')),
            ],
        ),
        migrations.CreateModel(
            name='placement_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('rced_batch_id', models.IntegerField()),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.AddField(
            model_name='participant_skill',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program_skill'),
        ),
        migrations.CreateModel(
            name='participant_project_cost_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CE', models.IntegerField()),
                ('WC', models.IntegerField()),
                ('total', models.IntegerField()),
                ('serial_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.participant_entre')),
            ],
        ),
        migrations.CreateModel(
            name='participant_perm_address_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_perm', models.CharField(blank=True, max_length=100)),
                ('state_perm', models.CharField(blank=True, max_length=25)),
                ('district_perm', models.CharField(blank=True, max_length=25)),
                ('pincode_perm', models.IntegerField()),
                ('city_perm', models.CharField(blank=True, max_length=25)),
                ('tehsil_perm', models.CharField(blank=True, max_length=25)),
                ('constituency_perm', models.CharField(blank=True, max_length=25)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_number_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_name_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=25)),
                ('full_name', models.CharField(blank=True, max_length=25)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_mobile_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField()),
                ('mobile_number', models.IntegerField(unique=True)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_mobile_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField(unique=True)),
                ('serial_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.participant_entre')),
            ],
        ),
        migrations.CreateModel(
            name='participant_job_details_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_exp_sector', models.CharField(blank=True, max_length=25)),
                ('no_of_months', models.IntegerField()),
                ('employed', models.CharField(blank=True, max_length=25)),
                ('employment_status', models.CharField(blank=True, max_length=25)),
                ('employment_details', models.CharField(blank=True, max_length=50)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_id_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(blank=True, max_length=25)),
                ('alt_id_type', models.CharField(blank=True, max_length=25)),
                ('aadhaar_ref_no', models.IntegerField(unique=True)),
                ('id_no', models.IntegerField(unique=True)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_ID_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_trainee', models.CharField(max_length=50)),
                ('father_or_husband_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('ID_proof', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.participant_entre')),
            ],
        ),
        migrations.CreateModel(
            name='participant_email_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.participant_entre')),
            ],
        ),
        migrations.CreateModel(
            name='participant_domicile_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom_state', models.CharField(blank=True, max_length=25)),
                ('dom_district', models.CharField(blank=True, max_length=25)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_disability_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_input', models.CharField(blank=True, max_length=25)),
                ('disability_type', models.CharField(blank=True, max_length=25)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_comm_address_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_comm', models.CharField(blank=True, max_length=100)),
                ('state_comm', models.CharField(blank=True, max_length=25)),
                ('district_comm', models.CharField(blank=True, max_length=25)),
                ('pincode_comm', models.IntegerField()),
                ('city_comm', models.CharField(blank=True, max_length=25)),
                ('tehsil_comm', models.CharField(blank=True, max_length=25)),
                ('constituency_comm', models.CharField(blank=True, max_length=25)),
                ('participant_id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant_skill')),
            ],
        ),
        migrations.CreateModel(
            name='participant_address_entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('serial_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.participant_entre')),
            ],
        ),
        migrations.CreateModel(
            name='dept_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('category_skill', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='category')),
            ],
        ),
    ]
