# Generated by Django 2.2.10 on 2021-05-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210511_1521'),
        ('core', '0002_auto_20210511_1553'),
    ]

    operations = [
    ]
