# Generated by Django 2.2.10 on 2021-05-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210513_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant_entre',
            old_name='mobile_entre_mobile_number',
            new_name='mobile_entre_number',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='mobile_skill_mobile_number',
            new_name='mobile_skill_number',
        ),
    ]
