# Generated by Django 2.2.10 on 2021-07-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210601_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant_entre',
            old_name='program_id',
            new_name='program_id_ent',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='program_id',
            new_name='program_id_skill',
        ),
        migrations.AlterUniqueTogether(
            name='participant_skill',
            unique_together={('program_id_skill', 'participant_id_skill')},
        ),
    ]
