# Generated by Django 2.2.10 on 2021-05-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210515_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_skill',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program_entre',
            name='program_name_ent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program_skill',
            name='depart_name_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dept_skill'),
        ),
        migrations.AlterField(
            model_name='program_skill',
            name='program_name_skill',
            field=models.CharField(max_length=100),
        ),
    ]
