# Generated by Django 2.2.10 on 2021-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210514_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_aadhaar_ref_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_alt_id_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_aadhaar_ref_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_alt_id_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
