# Generated by Django 2.2.10 on 2021-05-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210514_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant_entre',
            name='email',
        ),
    ]
