# Generated by Django 2.2.10 on 2021-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_entre',
            name='address_entre_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='address_entre_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='address_entre_state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='category_entre',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='date_of_loan_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='father_or_husband_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_aadhaar_ref_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='idcard_entre_alt_id_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='items_to_be_manufactured',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='job',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='mobile_entre_country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='mobile_entre_primary_mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='no_of_persons_employed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='own_contribution_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='place_of_unit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='primary_email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='project_cost_CE',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='project_cost_WC',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='project_identified',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='qualification',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='secondary_email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participant_entre',
            name='self_or_bank_financed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_address_comm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_city_comm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_constituency_comm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_district_comm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_pincode_comm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_state_comm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='comm_tehsil_comm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='disability_input',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='disability_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='domicile_district',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='domicile_state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='education_level',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='heard_about_us',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_aadhaar_ref_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='idcard_skill_alt_id_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='job_details_employed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='job_details_employment_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='job_details_employment_status',
            field=models.CharField(blank=True, choices=[('Employed Through Registered Employer', 'Employed Through Registered Employer'), ('Opted for Higher Studies', 'Opted for Higher Studies'), ('Self Employed', 'Self Employed'), ('Up Skilled', 'Up Skilled'), ('Employed', 'Employed'), ('NA', 'NA'), ('Employed at Training Partner', 'Employed at Training Partner'), ('Employed at Other Firm', 'Employed at Other Firm')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='job_details_no_of_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='job_details_prev_exp_sector',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single/Unmarried', 'Single/Unmarried'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Not to be Disclosed', 'Not to be Disclosed')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='mobile_skill_country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='mobile_skill_primary_mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='name_skill_LastName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='name_skill_salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mx', 'Mx')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='pa_same_as_ca',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_constituency',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_district',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='perm_tehsil',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='religion',
            field=models.CharField(blank=True, choices=[('Atheist', 'Atheist'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Jews', 'Jews'), ('Buddhism', 'Buddhism'), ('Zoroastrian', 'Zoroastrian'), ('Jainism', 'Jainism'), ('Not to be Disclosed', 'Not to be Disclosed')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='training_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='contact_person',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='contact_person_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='employer_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='job_position',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='job_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='other_benefit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='placement_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='reason',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
