# Generated by Django 2.2.10 on 2021-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210518_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_entre',
            name='primary_email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='participant_skill',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=50),
        ),
    ]
