# Generated by Django 2.2.10 on 2021-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_participant_entre_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_entre',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
