# Generated by Django 2.2.10 on 2021-05-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210518_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_address_comm',
            new_name='comm_address',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_city_comm',
            new_name='comm_city',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_constituency_comm',
            new_name='comm_constituency',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_district_comm',
            new_name='comm_district',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_pincode_comm',
            new_name='comm_pincode',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_state_comm',
            new_name='comm_state',
        ),
        migrations.RenameField(
            model_name='participant_skill',
            old_name='comm_tehsil_comm',
            new_name='comm_tehsil',
        ),
    ]
