# Generated by Django 2.2.10 on 2021-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210518_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_skill',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=50, null=True),
        ),
    ]
