# Generated by Django 2.2.10 on 2021-05-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210518_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_skill',
            name='Age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant_skill',
            name='Annual_income',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
