# Generated by Django 2.2.10 on 2021-05-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210519_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement_skill',
            name='id',
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='participant_id_skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.participant_skill'),
        ),
    ]
