# Generated by Django 2.2.10 on 2021-05-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210519_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_skill',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placement_skill',
            name='participant_id_skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.participant_skill'),
        ),
    ]
