# Generated by Django 2.2.10 on 2021-05-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dept_entre',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='prog_entre',
            fields=[
                ('program_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('financial_year', models.CharField(max_length=100)),
                ('no_of_participants', models.IntegerField(null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept_entre')),
            ],
        ),
    ]
