# Generated by Django 2.2.10 on 2021-05-06 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog_entre',
            name='department_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prog_entre',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2021, 5, 6, 14, 29, 2, 716599, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
