# Generated by Django 2.2.10 on 2021-05-06 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210506_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prog_entre',
            name='id',
        ),
        migrations.AlterField(
            model_name='prog_entre',
            name='financial_year',
            field=models.IntegerField(),
        ),
    ]
