# Generated by Django 2.2.10 on 2021-05-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210506_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dept_entre',
            options={'verbose_name_plural': 'department'},
        ),
        migrations.AlterField(
            model_name='dept_entre',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dept_entre',
            name='department_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prog_entre',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.dept_entre'),
        ),
        migrations.AlterField(
            model_name='prog_entre',
            name='department_name',
            field=models.CharField(default='NULL', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prog_entre',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
